# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-05 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(default=123, max_length=32),
        ),
    ]
