# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-06 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20180306_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='code',
            field=models.CharField(default='', max_length=32),
        ),
    ]
