# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-12 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('code', models.CharField(default='', max_length=32)),
                ('parent', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app02.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32)),
                ('menu', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app02.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('permissions', models.ManyToManyField(to='app02.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('pwd', models.CharField(default=123, max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('roles', models.ManyToManyField(to='app02.Role')),
            ],
        ),
        migrations.AddField(
            model_name='permission',
            name='permission_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app02.PermissionGroup'),
        ),
    ]
