# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
        ),
    ]
